name: CI Pipeline Docker

on:
  push:
    branches:[ "main" ]
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t balancee-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.GOODY_DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.GOODY_DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag balancee-app goodnessmark/blit-app:latest
          docker push goodnessmark/blit-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Staging with Docker
        run: |
          docker pull goodnessmark/balancee-app:latest
          docker run -d -p 80:3000 goodnessmark/blit-app:latest
